server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/trading?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

mybatis:
  mapper-locations:
    - classpath:/mybatis/mapper/**/*.xml
    - classpath*:/mybatis/mapper/**/*.xml
  type-aliases-package: com.trade.md.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    com.trade: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.stat: DEBUG

aes:
  key:

jwt:
  issuer: trading-auth
  secret:
  access-token-validity-seconds: 9000

trade:
  kis:
    key:
      secret: ${TRADE_KIS_KEY_SECRET:}
      app: ${TRADE_KIS_KEY_APP:}
    token:
      auth-domain-url: /oauth2/tokenP
      auth-domain: https://openapivts.koreainvestment.com:29443
      auth-disposal-url: /oauth2/revokeP
      auth-disposal-domain: https://openapivts.koreainvestment.com:29443
      skew-seconds: 60
      grant-type: client_credentials
    socket:
      url: /oauth2/Approval
      domain: https://openapivts.koreainvestment.com:29443
    url:
      current-price: https://openapivts.koreainvestment.com:29443/uapi/domestic-stock/v1/quotations/inquire-price
      inquire-daily-price : https://openapivts.koreainvestment.com:29443/uapi/domestic-stock/v1/quotations/inquire-daily-price

local:
  cmc:
    retry-kis-token: http://localhost:8081/api/kis/auth/oauth/token


run:
  internal:
    enabled: true
    token:
    protected-paths:
      - /v1/api/md/universe/ingest/**
