server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/trading?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

mybatis:
  mapper-locations: classpath:/mybatis/mapper/**/*.xml
  type-aliases-package: com.trade.catalog.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    com.trade: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.stat: DEBUG

aes:
  key:

jwt:
  issuer: trading-auth
  secret:
  access-token-validity-seconds: 9000
