server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/trading?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port:
      password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

#모의투자
trade:
  kis:
    key:
      secret:
      app:
    token:
      auth-domain-url: /oauth2/tokenP
      auth-domain: https://openapivts.koreainvestment.com:29443
      auth-disposal-url: /oauth2/revokeP
      auth-disposal-domain: https://openapivts.koreainvestment.com:29443
    socket:
      url: /oauth2/Approval
      domain: https://openapivts.koreainvestment.com:29443





logging:
  level:
    root: INFO
    com.trade: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.stat: DEBUG